import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/navbar";
import { SlideDown, SlideUp } from "@/components/slide";
import Footer from "@/components/footer";
import AsideContactMe from "@/components/aside";
import { Divider } from "antd";
import { Provider } from "@/components/darkTheme";

export const metadata: Metadata = {
  title: {
    absolute: "Home",
    template: "%s | mocoder",
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" >
      <body className="flex flex-col h-screen relative dark:bg-black">
        <Provider>
          <SlideDown>
            <Navbar />
            <Divider className="m-0"/>
          </SlideDown>
          <div className="flex-1 relative">
            <AsideContactMe />
            {children}
            <Divider className="m-0" />
          </div>
          <SlideUp>
            <Footer />
          </SlideUp>
        </Provider>
      </body>
    </html>
  );
}
